### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by PaulJohannFlade** [PaulJohannFlade/Capstone_ClanPlan#1]
## Value Proposition
**As a** family member,

**I want to** see a list of tasks,

**so that I** can quickly understand what needs to be done in our family.

## Description

![Image](https://github.com/PaulJohannFlade/Capstone_ClanPlan/assets/11298489/8ccdf4fa-12c5-4d4b-8e76-03dd0854bf91)

## Acceptance Criteria
- The header of the task list page shows the name of the App: "ClanPlan"
- The task list is headlined "Family Task List," highlighting its purpose.
- It displays task details including
  - `title`,
  - `category` (e.g., "Cleaning, "Errands"), 
  - `priority` (e.g., "High", "Medium", "Low"),
  - `due date`
- Tasks with current due dates are prominently highlighted.- 
- The list supports vertical scrolling to accommodate multiple entries.
- The tasks are sorted chronologically by it's due date.
-  If the list is empty, a message is displayed accordingly

### Tasks
- [ ] create feature branch `feature/task-list`
- [ ] create a `Header` component with a headline "ClanPlan"
- [ ] create the component TasksList to render a list with prop: `tasks`
- [ ] render the  `Header` component and `TasksList` component with props `tasks` from `db/lib/tasks.js` in `pages/index.js` 
- [ ] style the `TasksList` component with styled-components to display a vertical scrollbar list 
- [ ] create the component `TaskPreview` with props: `title`, `category`, `priority`, `dueDate`
- [ ] write a condition in `TaskPreview` component to highlight the tasks with current due dates with another style
- [ ] render `TaskPreview` component as a list element in `TasksList` component
- [ ] if the list is empty, display a message accordingly

**Comment by FelineHuhn** [comment]
Great first user story and well-considered tasks 🥳 I a few more suggestions:

1. Wireframe
- the wireframes look great 🤩
- both wireframes don't match adequate with the acceptance criteria: The first wireframe shows the headline on the top, but is not mentioned in the acceptance criteria. The second wireframe shows an error message which is also not included in the acceptance criteria. 
- Solution: Think about whether you want to include the app title and error message in this user story or not yet? Depending on this, the wireframe must be adjusted/removed or additional acceptance criteria must be added. Depending on the decision, the tasks may also have to be adjusted... Wireframes, acceptance criteria and tasks must always match each other :)

2. Acceptance criteria
- See my suggestion above
- As we already talked in your breakout room a few minutes ago, you could mention, that the tasks are sorted chronologically by it's due date

3. Tasks
- Well thought-out tasks! In future, you could even be a little less precise in order to retain a little more flexibility. But of course this will allow you to code faster and more consistently. So that's up to you :) 
- It could help generally to understand your tasks, when you use "``" to mark e.g. file names, component names etc. (for example: `TaskList` instead of TaskList component, instead of prop tasks, you could mark it as `tasks`)

**Comment by FelineHuhn** [comment]
Great improvement 🤩🥳 Just one tiny, but important thing left: The app title, which is shown in the wireframes is still not mentioned in the acceptance criteria. If you promise to include this accordingly, I'll give you my green tick 😆

**Comment by mariiaovs** [comment]
![image](https://github.com/PaulJohannFlade/Capstone_ClanPlan/assets/115471513/05c87be0-b81a-4fbe-b947-a11d8e6b1b99)
The app title is here in acceptance criteria, isnt't it?

**Comment by FelineHuhn** [comment]
I interpret this as the heading of the task list, or not? I mean the "ClanPlan" title in the wireframes...
