### ISSUE TITLE
Relax image - bugfix

### ISSUE THREAD

**Issue by PaulJohannFlade** [PaulJohannFlade/Capstone_ClanPlan#109]
## Value Proposition
**As a** family member,

**I want to**  see a picture from a relaxing turtle, if there are no tasks for me,

**so that** I can enjoy a pleasant visual and feel relaxed.

## Description

- bugfix responsive design

## Acceptance Criteria

- The displayed random image is not deformed.
- The random image has an describing alt tag.

### Tasks
- [ ] Create branch `feature/relaxImageBugFix`.
- [ ] add new alt-tag to random picture
- [ ] refine responsive design
