### ISSUE TITLE
Calendar page

### ISSUE THREAD

**Issue by mariiaovs** [PaulJohannFlade/Capstone_ClanPlan#26]
## Value Proposition
**As a** family member,

**I want to** have a calendar view  ,

**so that** i can see family tasks displayed on a calendar, making it easier to manage schedules and plan ahead

## Description

![Image](https://github.com/PaulJohannFlade/Capstone_ClanPlan/assets/115471513/d3ccdddc-dca2-4a74-b300-2eaeb65b3f2d)

## Acceptance Criteria
- Link "Calendar" in Home page navigates to the calendar page.
- Calendar page has a heading "My Calendar" calendar with default month view and a link to go back to the Home page.
- The family tasks are clearly visible in the corresponding dates in the calendar.
- User can change the due date of a task with drag and drop (only for desktop), due date can't be earlier than today date 
- Clicking a task in calender opens the task details page with back link to the calendar page

### Tasks
- [ ] create feature branch `feature/calendar`
- [ ] create a page `calendar/index.js` and render there a `Calendar` component from `react-big-calendar` with drag and drop and tasks in it
- [ ] add a link to calendar to the Home page
- [ ] implement a logic for drag and drop
- [ ] implement a logic to show Task Details page by its clicking
- [ ] style the calendar view
