### ISSUE TITLE
Recurring Task - edit

### ISSUE THREAD

**Issue by SwethaJanardhana** [PaulJohannFlade/Capstone_ClanPlan#54]
## Value Proposition
**As a** family member,

**I want to** be able to edit and update recurring tasks ,

**so that** I  can automate the process of scheduling repetitive tasks more efficiently

## Description

![Image](https://github.com/PaulJohannFlade/Capstone_ClanPlan/assets/151828170/4602891d-860c-47d2-bf2b-7043e3eb9c17)

When user selects `repeat` then `endDate` has to be selected until when the task has to repeat and by default it is set to today.

## Acceptance Criteria
- User has an option to edit and update a recurring task from the task details view
- Upon `Update` button click , user should have an option to update a single task or all the occurrences of a task, upon pop-up window confirmation

### Tasks
- Create a branch feature/recurring-edit
- At the backend server api adapt the code and implement the logic to update single or all the occurrences of a tasks
- At the frontend modify the task updating process with the pop-up window confirmation, so as to update single or all the occurrences of a tasks
- [ ]  Clicking on `No` button : implement logic to go back to `Task Details` view
- [ ]  Clicking on `This task`: implement logic to update current selected task and go back to `Task Details` view
- [ ]  Clicking on `All occurrences`: implement logic to update all the occurrences of  selected task and go back to `Task Preview` view

**Comment by ahohnsen** [comment]
A cool feature! 👍🏼 

Could you detail what happens when each of the three buttons is clicked? Except for the 'no' button, which saves data, what additional actions occur? Are users redirected to the overview or elsewhere? What happens if 'no' is chosen? Does it return users to the editing view?

**Comment by ahohnsen** [comment]
Apologies, perhaps I wasn't specific enough: The actions that occur when these buttons are clicked should be described more thoroughly in the acceptance criteria. Generally, all possible user interactions should be detailed in the acceptance criteria (and then, of course, without technical details/terms). 🙂
