### ISSUE TITLE
Edit Task

### ISSUE THREAD

**Issue by SwethaJanardhana** [PaulJohannFlade/Capstone_ClanPlan#6]
## Value Proposition
**As a** family member,

**I want to** edit tasks,

**so that** I can update any changes to tasks such as due dates, priorities.

## Description

![Image](https://github.com/PaulJohannFlade/Capstone_ClanPlan/assets/151828170/d8225145-a9ff-4eec-bbf9-06caf9dfd6dc)

## Acceptance Criteria
- An "Edit" button is associated with each task.
- Clicking "Edit" opens a form pre-filled with the task's existing details for modification with the heading "Edit a Task" indicating the forms purpose in another page.
- The header of the edit page shows the name of the App: "ClanPlan"
- The form allows editing all task aspects, including `title`, `category`, `priority` and `due date`.
- The edit page includes options for both saving  by clicking on the "Update" button and cancelling the action by clicking the back link. 
- The cancellation option allows the user to back out of the edit process if selected by mistake or changed mind.
- Submissions with empty required fields are blocked, with validation messages guiding completion.
- Changes are saved and the user is redirected to the task details page with updated task.

### Tasks
- [ ] create feature branch `feature/edit-task`
- [ ] create a `Link` with pen icon for each task in the TaskDetails component
- [ ] create a file pages/tasks/[id]/edit.js, which renders `Header` component and `Form` component with prop: defaultValues from current task
- [ ] clicking an Edit-Link routes to pages/tasks/[id]/edit.js with dynamic route
- [ ] write a function handleEditTask in _app.js with parameter updatedTask, which updates tasks list state with updated task, and pass this function to Form component on edit-page

**Comment by FelineHuhn** [comment]
Well structured and clearly formulated user story 🥳 Only thing I would recommend to update is the second acceptance criterium, since there is not only a form opening but the user navigates to a page, where the mentioned form is displayed.
