### ISSUE TITLE
user login for family members

### ISSUE THREAD

**Issue by mariiaovs** [PaulJohannFlade/Capstone_ClanPlan#65]
## Value Proposition
**As a** family member,

**I want to** create an own account in my family,

**so that** i am able to create, read, update and delete tasks for me and my family.

## Description

![Image](https://github.com/PaulJohannFlade/Capstone_ClanPlan/assets/11298489/a1489135-dd20-4d4e-a31b-1e0c5a746559)

## Acceptance Criteria
- On Hompage is a Sign In Button on Top right under the Header an if no User is signed in under a short description there is a second sign in Button
- clicking the Sign In Button shows Github login
- clicking the Sign In Button for the first time brings you to Github OAuth page
- clicking on the Log In Button with an existing account brings you back to the Homepage
- After signing in changes Sign in in Button in Sign out Button
- after signing in the hole user specific content from homepage is visible 
- click on Sign Out Button signs the user out

### Tasks
- [ ] create branch `feature/user-log-in-for-family-members`
- [ ] register a **OAuth-App** at Github
- [ ] implement basic Setup (npm install next-auth, define Api-route, Provide session context, Set the environment variables)
- [ ] configure `_app.js` to provide session-contex
- [ ] create Login and use `useSession hook `
- [ ] Build Collection for users in MongoDB
- [ ] Create schema and models for user in /db/models
- [ ] create dynamic route `pages/api/user/[id]` and handle methods: GET and POST
- [ ] configure `_app.js` to provide session-context 
- [ ] secure Backend
- [ ] personalize Data

[NextAuth Workshop Repo 1](https://github.com/Roland-Hufnagel/Workshop-Next-Auth)
[NextAuth Workshop Repo 2](https://github.com/NikRoe/nextauth-demo-codealong)
