### ISSUE TITLE
Send Email

### ISSUE THREAD

**Issue by SwethaJanardhana** [PaulJohannFlade/Capstone_ClanPlan#89]
## Value Proposition
**As a** family member,

**I want to** send the notification to the newly added member,

**so that** the member gets to know that he/she belongs to this family.

## Description

![Image](https://github.com/PaulJohannFlade/Capstone_ClanPlan/assets/151828170/1a1aea09-5b2d-453a-9161-c185171dcaf5)

## Acceptance Criteria
-  When a new member is added to the family he/she should receive a notification in the form of email.
-  Modify the `Add a new family member` form to include the email, so as to link with the family Id.
 

### Tasks
- [ ]  create a branch feature/email
- [ ]  Modify the `MemberForm.js` component to include the email input field.
- [ ] Configure ÈmailJS`
- [ ] Upon clicking a on "Click here" button a modal window form "Add Family" opens up with `Family Name` text field and `Your Role` dropdown with the options - Please select a role, Parent, Kid, Caregiver and a `Add` button
- [ ] Implement the logic to add the family both at the frontend and the backend
- [ ] Also implement the logic to add this user as the family member both at the frontend and the backend
