### ISSUE TITLE
relax - image for today (3-5 random?)

### ISSUE THREAD

**Issue by PaulJohannFlade** [PaulJohannFlade/Capstone_ClanPlan#98]
## Value Proposition
**As a** family member,

**I want to** , see a picture from a relaxing turtle, if there are no Tasks for me

**so that** i know there is nothing to do for me today.

## Description

![Image](https://github.com/PaulJohannFlade/Capstone_ClanPlan/assets/11298489/6c9a55c8-ea27-4fa5-93c3-cb1e1a3a625d)

## Acceptance Criteria
- There is a public/images directory that contains at least 4 image files (e.g. image1.jpg, image2.jpg, image3.jpg).
- When the start page (/ or index.js) is loaded, an image is randomly selected from the public/images directory and displayed.
- The random selection is made from a predefined list of image names.
- The selected image is displayed correctly on the start page.
- The image is displayed with an img tag that points the source (src) to the corresponding image in the public/images directory.
- The alt text of the image is “Random”.
- There is a React component RandomImage that contains the logic for random image selection and display.
- The component uses React Hooks (useState, useEffect) to manage the random image state and to select an image during initialization.
- Each time the start page is reloaded, a different (randomly selected) image is displayed.
- The random mechanism works correctly and shows an even distribution of images over several reloads.

### Tasks
- [ ] Create a directory in your project that contains the images, e.g. public/images.
- [ ] Define a list of image names in your code.
- [ ] Implementiere eine Funktion, die zufällig ein Bild aus der Liste auswählt.
- [ ] Create a component that displays the randomly selected image.
